<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXoxnij5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXoxnij5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXoxnij5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXoxnij5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXoxnij5\appProdProjectContainer([
    'container.build_hash' => 'Xoxnij5',
    'container.build_id' => '2e8e0197',
    'container.build_time' => 1636025707,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXoxnij5');
