<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0px4yz5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0px4yz5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0px4yz5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0px4yz5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0px4yz5\appDevDebugProjectContainer([
    'container.build_hash' => '0px4yz5',
    'container.build_id' => '8f813323',
    'container.build_time' => 1636507159,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0px4yz5');
